### ISSUE TITLE
Restrict secp*r1 curves

### ISSUE THREAD

**Issue by msporny** [w3c/vc-jws-2020#16]
The following secp*r1 curves are supported currently:

> EC	P-256	ES256
> EC	P-384	ES384
> EC	P-521	ES512

The whole point with year-stamped cryptographic suites is to pick *one* option that makes sense for that year. I suggest P-384, since it seems to meet all national and enterprise standards across the globe.

**Comment by kdenhartog** [comment]
I'm good with that. Last I heard @troyronda may have a requirement for P-256/ES256 as well. Definitely don't think we need P-521/ES512 support here.

I like the idea of restricting on curve where possible

**Comment by troyronda** [comment]
We are using the JWS LDS suite with P-256 curves.

**Comment by OR13** [comment]
I agree we can probably drop P-521/ES512... I'm not sure its helpful to drop `EC P-256 ES256` and `EC P-384 ES384`... as I understand it, both are used widely in legacy systems... 

I would be in favor of Jws2021 having dropping to only support for `EC P-384 ES384` on the NIST Curve front.

**Comment by OR13** [comment]
The intention of this suite is to support as much of the IANA registry is possible, this isn't the place to make value judgements about registered alg values.

**Comment by msporny** [comment]
> The intention of this suite is to support as much of the IANA registry is possible, this isn't the place to make value judgements about registered alg values.

-1 to closing, if the purpose of this cryptosuite has changed to now "support as much of the IANA registry as possible", I expect there will a fair number of objections raised on that approach (too much algorithm agility, large security attack surface, complex implementations, required algorithms for interop testing, etc.).

**Comment by kdenhartog** [comment]
I'm definitely staying subscribed for this debate 😄 

![eat popcorn](https://media.giphy.com/media/2UvAUplPi4ESnKa3W0/giphy.gif)

**Comment by OR13** [comment]
@msporny The purpose of the crypto suite has not changed, it was always meant to respect IETF and IANA... it was never meant to replace them... I look forward to this debate, it's about time the W3C stopped pretending its the CFRG.

![tumblr_myz4pvk1nF1schu5jo1_500](https://user-images.githubusercontent.com/8295856/184264882-900af49f-5f48-41b7-9ab0-a803ad68912f.gif)

**Comment by msporny** [comment]
> The purpose of the crypto suite has not changed

At present, the JWS 2020 cryptosuite contains this section:

https://w3c.github.io/vc-jws-2020/#jose-conformance

That is, it restricts the number of signature algorithms in the JOSE registry to a subset of 6 of them. Then, earlier in this thread, you state:

> The intention of this suite is to support as much of the IANA registry is possible

The IANA registry contains ~20 digital signature algorithms... if the intent is to support "as much of them as possible", then the purpose of the crypto suite has changed.

> it was always meant to respect IETF and IANA... it was never meant to replace them... I look forward to this debate, it's about time the W3C stopped pretending its the CFRG.

Excessive algorithm agility has been a topic of concern in the CFRG for a while, the Data Integrity cryptosuites were designed to address concerns raised in the CFRG over the past decade. Misrepresenting the purpose of the work in a way that is needlessly combative (e.g., "W3C vs. CFRG") is not helpful... the CFRG is listed as a liason to the VCWG and is there to ensure that we take their guidance when performing this work. We are working in concert with the CFRG.

**Comment by OR13** [comment]
@msporny I agree that positioning JOSE and cryptographic agility as harmful is needlessly combative... We've had this debate several times... You have called JOSE a footgun repeatedly... You don't seem to appreciate the amount of success and adoption it has... these are factors we are trying to build on here.

Again, this suite was created so that there would not be a need to "create a new Data Integrity Spec" every time IANA admits a new algorithm... as they are likely to do in the future... because all cryptography has a shelf life, and new suite are invented every year.

You are proposing a limitation which destroys the utility and intention of the suite.

It is true that the suite defines key formats that support the existing `alg` fields registered with IANA today.

The type of `publicKeyJwk` is `@json`... It's not "only the curve types Manu / CCG like".

We are not here to create "policy" we are here to create standards that allow policy makers to be clear regarding what they support... If its you policy to only use DJB curves... thats fine, you can use this suite with that policy... If you are required to only support ES256 on HSMs... great you can use this suite... IANA defines the terms behind these decisions.

If W3C keeps trying to embed values in registries, it's going to make itself a political pariah. 

Pointing to the JOSE registry to say that it defines the various valuea for `alg` is the right thing to do.

Pointing to the registry and then saying that `publicKeyJwk` is somehow being profiled with the W3C... is the wrong thing to do.

We need to keep the layers clear or political issues in one layer, will pull the whole thing apart.
